In [4]:
#Numpy Array

height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

# Import the numpy package as np
import numpy as np

# Create 2 numpy arrays from height and weight
np_height = np.array(height)
np_weight = np.array(weight)
print(np_height)#prints numpy array of height
print(np_weight)#prints numpy array of weight
print(type(np_height))#print the type of array


[1.87 1.87 1.82 1.91 1.9  1.85]
[81.65 97.52 95.25 92.98 86.18 88.45]
<class 'numpy.ndarray'>


In [5]:
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]
import numpy as np

# Create 2 numpy arrays from height and weight
np_height = np.array(height)
np_weight = np.array(weight)
print(np_height)#prints numpy array of height
print(np_weight)#prints numpy array of weight
print(type(np_height))#print the type of array
# Calculate bmi
bmi = np_weight / np_height ** 2

# Print the result
print(bmi)  
# For a boolean response
bmi > 23

# Print only those observations above 23
bmi[bmi > 23]   #prints the bmi results greater than 23

[1.87 1.87 1.82 1.91 1.9  1.85]
[81.65 97.52 95.25 92.98 86.18 88.45]
<class 'numpy.ndarray'>
[23.34925219 27.88755755 28.75558507 25.48723993 23.87257618 25.84368152]


array([23.34925219, 27.88755755, 28.75558507, 25.48723993, 23.87257618,
       25.84368152])

In [6]:
weight_kg = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

import numpy as np

# Create a numpy array np_weight_kg from weight_kg
np_weight_kg = np.array(weight_kg)

# Create np_weight_lbs from np_weight_kg
np_weight_lbs = np_weight_kg * 2.2

# Print out np_weight_lbs
print(np_weight_lbs)#this will print the result of np_weight_lbs which will 2.2 times multiple of actual

[179.63  214.544 209.55  204.556 189.596 194.59 ]


In [7]:
#pandas examples
 #pandas series
import pandas as pd  
x = pd.Series() #creates an Empty Series type object that has no values and having default datatype, i.e., float64. 
print (x)  

Series([], dtype: float64)


In [8]:
import pandas as pd  
import numpy as np  
info = np.array(['P','a','n','d','a','s'])  #creates series with input values of numpy array and datatype as object
a = pd.Series(info)  
print(a)   

0    P
1    a
2    n
3    d
4    a
5    s
dtype: object


In [10]:
#import the pandas library   
import pandas as pd  
import numpy as np  
info = {'x' : 0., 'y' : 1., 'z' : 2.} #creates series from dictionaries 
a = pd.Series(info)  
print (a)  #prints the created series from dictionaries

x    0.0
y    1.0
z    2.0
dtype: float64


In [11]:
#import pandas library   
import pandas as pd  
import numpy as np  
x = pd.Series(4, index=[0, 1, 2, 3]) #creates series from scalars 
print (x)  #prints the created series using scalars

0    4
1    4
2    4
3    4
dtype: int64


In [12]:
import pandas as pd  
x = pd.Series([1,2,3],index = ['a','b','c'])  #this will access data from position
#retrieve the first element  
print (x[0])  #prints the data accessed according to the position[0]ie 1

1


In [13]:
dict = {"country": ["Brazil", "Russia", "India", "China", "South Africa"],
       "capital": ["Brasilia", "Moscow", "New Dehli", "Beijing", "Pretoria"],
       "area": [8.516, 17.10, 3.286, 9.597, 1.221],
       "population": [200.4, 143.5, 1252, 1357, 52.98] }

import pandas as pd
brics = pd.DataFrame(dict)#creates the data frame of the given dictionary
print(brics)#prints the data frame of the dictionary

        country    capital    area  population
0        Brazil   Brasilia   8.516      200.40
1        Russia     Moscow  17.100      143.50
2         India  New Dehli   3.286     1252.00
3         China    Beijing   9.597     1357.00
4  South Africa   Pretoria   1.221       52.98


In [14]:
brics.index = ["BR", "RU", "IN", "CH", "SA"]#creates index to the dictionary
print(brics)#prints the dataframe according to index 

         country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Dehli   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98


In [18]:
import pandas as pd  
data = {'Name': ['Smith', 'Parker'], 'ID': [101, 102], 'Language': ['Python', 'JavaScript']}  
info = pd.DataFrame(data)  
print('DataFrame Values:\n', info)  #prints the csv dataframes values from info
# default CSV  
csv_data = info.to_csv()  
print('\nCSV String Values:\n', csv_data) #prints the string values  from csv_data 

DataFrame Values:
      Name   ID    Language
0   Smith  101      Python
1  Parker  102  JavaScript

CSV String Values:
 ,Name,ID,Language
0,Smith,101,Python
1,Parker,102,JavaScript



FileNotFoundError: [Errno 2] File b'cars.csv' does not exist: b'cars.csv'